services:
    _defaults:
        autowire: true
        autoconfigure: true

    RmAuthenticatorBundle\:
        resource: '../../../../src/RmAuthenticatorBundle/*'
        exclude: '../../../../src/RmAuthenticatorBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    RmAuthenticatorBundle\Controller\:
        resource: '../../../../src/RmAuthenticatorBundle/Controller'
        tags: ['controller.service_arguments']

    RmAuthenticatorBundle\Authenticator\Factory:
        class: RmAuthenticatorBundle\Authenticator\Factory
        arguments:
            $settings:
                sandbox: true
                default: Facebook

            $gateways:
                Facebook:
                    gateway: RmAuthenticatorBundle\Authenticator\Gateways\Facebook\Gateway
                    options:
                        app_id: "test123"
                        secret: "test123"
                        default_graph_version: "v2.10"
                Twitter:
                    gateway: RmAuthenticatorBundle\Authenticator\Gateways\Twitter\Gateway
                    options:
                        client_id: "test123"
                        secret: "test123"
                        consumer_key: "test123"
                        consumer_secret: "test123"
                GitHub:
                    gateway: RmAuthenticatorBundle\Authenticator\Gateways\GitHub\Gateway
                    options:
                        client_id: "test123"
                        secret: "test123"

